# GoReleaser configuration for domain-scan
version: 1

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: ./main_new.go
    binary: domain-scan
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: arm
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - config.yaml

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  draft: false
  prerelease: auto
  name_template: "Release {{.Version}}"
  header: |
    ## Release {{.Version}}
    
    **Full Changelog**: https://github.com/valllabh/domain-scan/compare/{{ .PreviousTag }}...{{ .Tag }}
  footer: |
    ## Installation
    
    ### Binary Downloads
    Download the appropriate binary for your platform from the assets below.
    
    ### Package Managers
    ```bash
    # Homebrew (macOS/Linux)
    brew install valllabh/tap/domain-scan
    
    # APT (Debian/Ubuntu)
    wget https://github.com/valllabh/domain-scan/releases/download/{{.Tag}}/domain-scan_amd64.deb
    sudo dpkg -i domain-scan_amd64.deb
    
    # RPM (RHEL/CentOS/Fedora)
    wget https://github.com/valllabh/domain-scan/releases/download/{{.Tag}}/domain-scan_amd64.rpm
    sudo rpm -i domain-scan_amd64.rpm
    ```
    

brews:
  - name: domain-scan
    repository:
      owner: valllabh
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/valllabh/domain-scan
    description: "Comprehensive domain asset discovery tool"
    license: MIT
    test: |
      system "#{bin}/domain-scan", "version"
    dependencies:
      - name: go
        type: optional

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage: https://github.com/valllabh/domain-scan
    description: |-
      Comprehensive domain asset discovery tool that combines
      passive subdomain enumeration, TLS certificate analysis,
      and HTTP service verification.
    maintainer: Domain-scan Team <team@domain-scan.io>
    license: MIT
    vendor: Domain-scan
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./config.yaml
        dst: /etc/domain-scan/config.yaml
        type: "config|noreplace"
    formats:
      - apk
      - deb
      - rpm

