# GoReleaser configuration for domain-scan
version: 1

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./main_new.go
    binary: domain-scan
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - config.yaml

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: domain-scan
    name: domain-scan
  draft: true
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"

brews:
  - name: domain-scan
    repository:
      owner: domain-scan
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/domain-scan/domain-scan
    description: "Comprehensive domain asset discovery tool"
    license: MIT
    test: |
      system "#{bin}/domain-scan", "version"
    dependencies:
      - name: go
        type: optional

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage: https://github.com/domain-scan/domain-scan
    description: |-
      Comprehensive domain asset discovery tool that combines
      passive subdomain enumeration, TLS certificate analysis,
      and HTTP service verification.
    maintainer: Domain-scan Team <team@domain-scan.io>
    license: MIT
    vendor: Domain-scan
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./config.yaml
        dst: /etc/domain-scan/config.yaml
        type: "config|noreplace"
    formats:
      - apk
      - deb
      - rpm

# snapcrafts:
#   - name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
#     summary: Comprehensive domain asset discovery tool
#     description: |
#       Domain-scan is a comprehensive web asset discovery tool that combines
#       passive subdomain enumeration, TLS certificate analysis, and HTTP service
#       verification to provide complete visibility into domain infrastructure.
#     grade: stable
#     confinement: strict
#     publish: false
#     license: MIT

# dockers:
#   - image_templates:
#       - "ghcr.io/domain-scan/domain-scan:{{ .Version }}-amd64"
#       - "ghcr.io/domain-scan/domain-scan:latest-amd64"
#     dockerfile: Dockerfile
#     use: buildx
#     build_flag_templates:
#       - "--pull"
#       - "--label=org.opencontainers.image.created={{.Date}}"
#       - "--label=org.opencontainers.image.title={{.ProjectName}}"
#       - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#       - "--label=org.opencontainers.image.version={{.Version}}"
#       - "--platform=linux/amd64"
#   - image_templates:
#       - "ghcr.io/domain-scan/domain-scan:{{ .Version }}-arm64v8"
#       - "ghcr.io/domain-scan/domain-scan:latest-arm64v8"
#     dockerfile: Dockerfile
#     use: buildx
#     build_flag_templates:
#       - "--pull"
#       - "--label=org.opencontainers.image.created={{.Date}}"
#       - "--label=org.opencontainers.image.title={{.ProjectName}}"
#       - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#       - "--label=org.opencontainers.image.version={{.Version}}"
#       - "--platform=linux/arm64/v8"
#     goarch: arm64

# docker_manifests:
#   - name_template: "ghcr.io/domain-scan/domain-scan:{{ .Version }}"
#     image_templates:
#       - "ghcr.io/domain-scan/domain-scan:{{ .Version }}-amd64"
#       - "ghcr.io/domain-scan/domain-scan:{{ .Version }}-arm64v8"
#   - name_template: "ghcr.io/domain-scan/domain-scan:latest"
#     image_templates:
#       - "ghcr.io/domain-scan/domain-scan:latest-amd64"
#       - "ghcr.io/domain-scan/domain-scan:latest-arm64v8"